name: My First Workflow

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 1 step
        run: echo "안녕하세요"

      - name: 2 step
        run: date

      - name: 3 step
        run: echo "${{ github.actor }} 님"